export const aiCarrierConfig = {
  aiCarrierMinCommitMs: 350,
  aiCarrierMaxCommitMs: 1400,
  aiCarrierReevaluateAfterMs: 650,
  aiCarrierTargetChangeThreshold: 80,
  aiCarrierAngleChangeThresholdRadians: 0.65,
  aiAimSmoothingEnabled: true,
  aiAimTurnRateRadiansPerSec: 6,
  aiAimDeadzoneRadians: 0.08,
  aiPreventAimFlipFlop: true,
  freezeCarrierTacticalJob: true,
  carrierTacticReevalMs: 650,
  aiCarrySideCommitMs: 900,
  aiCarryToAngleDistance: 110,
  aiCarryStuckSpeedThreshold: 0.4,
  aiCarryStuckTimeMs: 600,
  aiMaxCarryMs: 1800,
  aiReleaseSafetyLeadMs: 120,
  aiForceReleaseWhenStuck: true,
  aiSpinDetectionEnabled: true,
  aiSpinAngularVelocityThreshold: 4.5,
  aiSpinDurationMs: 500,
  aiSpinForceRelease: true,
} as const
