export const aiConfig = {
  seekCoreRadius: 520,
  supportSpacing: 230,
  strikerAttackDistance: 310,
  keeperHomeRadius: 210,
  keeperAggression: 0.62,
  brutePressureRadius: 132,
  bruteCheckRadius: 72,
  bruteCheckCooldownMs: 1500,
  bruteFumblePressure: 0.55,
  passPreference: 0.78,
  shotPreference: 0.86,
  aiCradleRadius: 105,
  aiReleaseDelayMs: 560,
  humanSwitchIntervalMs: 180,
  humanPreferStrikerDistance: 150,
  formationResetDelayMs: 650,
  passLeadDistance: 30,
  passSpread: 42,
  shotSpread: 55,
  offBallAimMinimumDistance: 48,
  offBallAimMaxTurnRate: 4.2,
  roleBehavior: {
    keeperReactionMin: 0.78,
    keeperReactionMax: 1,
    controlCatchMin: 0.82,
    controlCatchMax: 1.08,
    reactionSwingMin: 0.8,
    reactionSwingMax: 1.05,
    strikerPassAdvantageDistance: 125,
    strikerReceiveGoalBlend: 0.7,
    supportShotDistance: 300,
    supportOpenLaneRadius: 165,
    supportRetreatBlend: 0.22,
    bruteGuardGoalBlend: 0.42,
    attributeChargeMin: 0.88,
    attributeChargeMax: 1.08,
  },
  debug: {
    targetRadius: 9,
    targetAlpha: 0.72,
    pathAlpha: 0.36,
  },
} as const
