export const aiOffenseConfig = {
  aiBankShotsEnabled: true,
  aiBankShotPreference: 0.35,
  aiBankShotMinScore: 0.45,
  aiBankShotMaxAngleError: 0.35,
  aiBankShotWallPadding: 35,
  aiBankShotBlockedPenalty: 0.35,
  aiBankShotGoaliePenalty: 0.25,
  aiBankShotStyleBonusForTechnical: 0.15,
  aiBankShotStyleBonusForBankHunter: 0.25,
  aiSeekBetterShotAngleEnabled: true,
  aiShotBlockedThreshold: 0.55,
  aiLateralAttackMoveStrength: 0.65,
  aiLateralShotAngleTargetDistance: 110,
  aiBehindGoalPassEnabled: true,
  aiFrontSlotPassEnabled: true,
  aiShotPatienceMs: 650,
  aiForceShotAfterMs: 1800,
  behindGoalPassEnabled: true,
  behindGoalPassScoreBonus: 0.25,
  frontSlotReceiverScoreBonus: 0.3,
  passBackToFrontEnabled: true,
  passBackMinLaneScore: 0.42,
  keeperPulledOutOfPositionBonus: 0.2,
}
