export const clearSafetyConfig = {
  ownGoalPreventionEnabled: true,
  ownGoalClearPathCheckEnabled: true,
  ownGoalDangerConeRadians: 0.95,
  ownGoalClearMinAwayDot: 0.4,
  safeClearSideBias: 0.4,
  safeClearMidfieldBias: 0.65,
  safeClearTeammateBias: 0.25,
  safeClearRandomVariance: 0.12,
  blockClearIntoOwnGoalHard: true,
  defensiveDeflectionSafetyEnabled: true,
  defensiveDeflectionAwayBias: 0.85,
  keeperShieldAwayBias: 0.95,
  defenderStickAwayBias: 0.72,
  nearOwnGoalSafetyRadius: 320,
}
