export const clearSafetyConfig = {
  ownGoalPreventionEnabled: true,
  ownGoalClearPathCheckEnabled: true,
  ownGoalDangerConeRadians: 0.9,
  ownGoalClearMinAwayDot: 0.4,
  ownGoalProjectionDistance: 260,
  safeClearSideBias: 0.6,
  safeClearMidfieldBias: 0.45,
  safeClearTeammateBias: 0.25,
  safeClearRandomVariance: 0.12,
  blockClearIntoOwnGoalHard: true,
  defensiveDeflectionSafetyEnabled: true,
  defensiveDeflectionAwayBias: 0.85,
  keeperShieldAwayBias: 0.92,
  defenderStickAwayBias: 0.75,
  nearOwnGoalSafetyRadius: 300,
  ownGoalPanicClearPowerScale: 0.85,
}
