export const gatherConfig = {
  activeGatherEnabled: true,
  activeGatherRadius: 96,
  activeGatherStrength: 0.7,
  activeGatherMaxSpeed: 19,
  activeGatherFunnelAngle: 1.9,
  activeGatherSnapRadius: 52,
  activeGatherSnapEnabled: true,
  passiveGatherEnabled: true,
  passiveGatherRadius: 58,
  passiveGatherStrength: 0.32,
  passiveGatherMaxSpeed: 11,
  passiveGatherFunnelAngle: 1.25,
  humanCloseGatherRadius: 38,
  humanPassiveCloseGatherRadius: 26,
  releaseRegrabCooldownMs: 180,
  fumbleRegrabCooldownMs: 260,
  gatherAttemptCooldownMs: 20,
  failedGatherGraceMs: 220,
  gatherOverridesStanceReset: true,
  catchReadyMinHoldMs: 70,
  catchReadyExitDelayMs: 120,
  stanceResetDoesNotCancelGather: true,
} as const
