export const gatherConfig = {
  activeGatherEnabled: true,
  activeGatherRadius: 84,
  activeGatherStrength: 0.58,
  activeGatherMaxSpeed: 16,
  activeGatherFunnelAngle: 1.65,
  activeGatherSnapRadius: 44,
  activeGatherSnapEnabled: true,
  passiveGatherEnabled: true,
  passiveGatherRadius: 52,
  passiveGatherStrength: 0.26,
  passiveGatherMaxSpeed: 9.5,
  passiveGatherFunnelAngle: 1.1,
  humanCloseGatherRadius: 30,
  releaseRegrabCooldownMs: 180,
  fumbleRegrabCooldownMs: 260,
  gatherAttemptCooldownMs: 30,
  failedGatherGraceMs: 160,
  gatherOverridesStanceReset: true,
  catchReadyMinHoldMs: 120,
  catchReadyExitDelayMs: 80,
  stanceResetDoesNotCancelGather: true,
} as const
