export const gatherConfig = {
  activeGatherEnabled: true,
  activeGatherRadius: 72,
  activeGatherStrength: 0.42,
  activeGatherMaxSpeed: 13.5,
  activeGatherFunnelAngle: 1.25,
  activeGatherSnapRadius: 34,
  activeGatherSnapEnabled: true,
  passiveGatherEnabled: true,
  passiveGatherRadius: 42,
  passiveGatherStrength: 0.18,
  passiveGatherMaxSpeed: 7.5,
  passiveGatherFunnelAngle: 0.75,
  releaseRegrabCooldownMs: 180,
  fumbleRegrabCooldownMs: 260,
  gatherAttemptCooldownMs: 45,
  failedGatherGraceMs: 90,
  gatherOverridesStanceReset: true,
  catchReadyMinHoldMs: 120,
  catchReadyExitDelayMs: 80,
  stanceResetDoesNotCancelGather: true,
} as const
