export const playerRuntimeConfig = {
  radius: 21.5,
  baseMaxSpeed: 6.35,
  accelerationPerSecond: 38,
  brakingPerSecond: 52,
  facingTurnRateRadiansPerSecond: 8.5,
  frictionAir: 0.18,
  restitution: 0.35,
  controlledIndicatorRadius: 35,
  roleLabelOffsetY: 41,
  aiStateLabelOffsetY: 58,
  teamAColor: 0x42d8ff,
  teamAAccent: 0xffd35c,
  teamBColor: 0xff5f7a,
  teamBAccent: 0xb6ff68,
} as const
