export const spacingConfig = {
  maxCorePressersPerTeam: 1,
  presserSwitchCooldownMs: 900,
  presserDistanceAdvantageRequired: 60,
  supportMinSpacingFromCarrier: 140,
  supportPreferredSpacing: 210,
  avoidClusterRadius: 130,
  teammateRepulsionStrength: 0.45,
  possessionOffenseTransitionMs: 220,
  possessionDefenseTransitionMs: 400,
  offenseSupportMinSpacingFromCarrier: 158,
  offenseSupportPreferredSpacing: 240,
  offenseAvoidClusterRadius: 152,
  offenseTeammateRepulsionStrength: 0.6,
  avoidanceMaxInfluence: 0.45,
  openLaneWeight: 0.65,
  behindGoalLaneWeight: 0.55,
  defensiveCoverWeight: 0.5,
  enableBehindGoalCuts: true,
  behindGoalCutChanceSupport: 0.35,
  behindGoalCutChanceStriker: 0.45,
  frontSlotSpacing: 120,
  behindGoalSpacing: 70,
  bankShotPreference: 0.35,
  debug: {
    presserColor: 0xff6b7a,
    outletColor: 0x69ecff,
    coverColor: 0xffd24f,
    behindGoalColor: 0xc99cff,
    frontSlotColor: 0x8df0cf,
    targetRadius: 11,
  },
} as const
