export const spacingConfig = {
  maxCorePressersPerTeam: 1,
  presserSwitchCooldownMs: 780,
  presserDistanceAdvantageRequired: 60,
  supportMinSpacingFromCarrier: 150,
  supportPreferredSpacing: 235,
  avoidClusterRadius: 148,
  teammateRepulsionStrength: 0.52,
  possessionOffenseTransitionMs: 220,
  possessionDefenseTransitionMs: 400,
  offenseSupportMinSpacingFromCarrier: 185,
  offenseSupportPreferredSpacing: 295,
  offenseAvoidClusterRadius: 178,
  offenseTeammateRepulsionStrength: 0.74,
  avoidanceMaxInfluence: 0.52,
  openLaneWeight: 0.78,
  behindGoalLaneWeight: 0.66,
  defensiveCoverWeight: 0.5,
  enableBehindGoalCuts: true,
  behindGoalCutChanceSupport: 0.35,
  behindGoalCutChanceStriker: 0.45,
  frontSlotSpacing: 155,
  behindGoalSpacing: 90,
  bankShotPreference: 0.42,
  debug: {
    presserColor: 0xff6b7a,
    outletColor: 0x69ecff,
    coverColor: 0xffd24f,
    behindGoalColor: 0xc99cff,
    frontSlotColor: 0x8df0cf,
    targetRadius: 11,
  },
} as const
