import type { StickStyle } from '../data/matchTypes'

export const stickVisualConfig = {
  generatedTexturePrefix: 'spincore-cesta-bat-v4',
  textureWidth: 108,
  textureHeight: 82,
  rootX: 9,
  centerY: 40,
  pocketAnchorX: 76,
  pocketAnchorY: 51,
  totalStickLength: 78,
  handleLength: 14,
  handleWidth: 9,
  neckLength: 14,
  neckWidth: 12,
  pocketWidth: 30,
  pocketDepth: 31,
  lipThickness: 10,
  innerHighlightWidth: 4,
  outlineWidth: 3.5,
  woodGrainAlpha: 0,
  pocketWeaveAlpha: 0.16,
  pocketWidthScale: 1,
  lipThicknessScale: 1,
  handleLengthScale: 1,
  innerHighlightAlpha: 0.82,
  outlineAlpha: 0.96,
  shadowAlpha: 0.24,
  visualScaleByStyle: {
    hook: 0.98,
    cradle: 0.97,
    hammer: 0.98,
    whip: 0.96,
    fork: 0.97,
  } satisfies Record<StickStyle, number>,
  swingTrailAlpha: 0.54,
  swingTrailDurationMs: 155,
  swingTrailWidth: 6,
  pocketGlowRadius: 15,
  pocketForegroundWidth: 5,
  impactFlashMs: 90,
} as const
