import type { StickStyle } from '../data/matchTypes'

export const stickVisualConfig = {
  generatedTexturePrefix: 'spincore-cesta-bat-v2',
  textureWidth: 112,
  textureHeight: 80,
  rootX: 10,
  centerY: 38,
  pocketAnchorX: 81,
  pocketAnchorY: 49,
  totalStickLength: 84,
  handleLength: 16,
  handleWidth: 9,
  neckLength: 17,
  neckWidth: 11,
  pocketWidth: 27,
  pocketDepth: 29,
  lipThickness: 9,
  innerHighlightWidth: 4,
  outlineWidth: 3,
  woodGrainAlpha: 0.08,
  pocketWidthScale: 1,
  lipThicknessScale: 1,
  handleLengthScale: 1,
  innerHighlightAlpha: 0.82,
  outlineAlpha: 0.96,
  shadowAlpha: 0.24,
  visualScaleByStyle: {
    hook: 0.96,
    cradle: 0.95,
    hammer: 0.96,
    whip: 0.93,
    fork: 0.94,
  } satisfies Record<StickStyle, number>,
  swingTrailAlpha: 0.54,
  swingTrailDurationMs: 155,
  swingTrailWidth: 6,
  pocketGlowRadius: 15,
  pocketForegroundWidth: 5,
  impactFlashMs: 90,
} as const
