import { playerArchetypes } from '../data/playerArchetypes'
import { teams } from '../data/teams'
import type { LabTuningState } from '../lab/LabConfig'

export function createDefaultLabTuning(): LabTuningState {
  const players: LabTuningState['players'] = Object.fromEntries(
    teams.flatMap((team) =>
      team.roster.map((entry) => [
        entry.id,
        {
          id: entry.id,
          role: entry.role,
          playStyle: entry.playStyle,
          handedness: entry.handedness,
          stickStyle: entry.stickStyle,
          attributes: {
            ...playerArchetypes[entry.archetypeId].attributes,
          },
          defenseTendencies: defaultDefenseTendencies(entry.role),
        },
      ]),
    ),
  )
  const controlledStriker = players['a-striker']

  if (controlledStriker) {
    controlledStriker.role = 'striker'
    controlledStriker.playStyle = 'aggressive'
    controlledStriker.handedness = 'right'
    controlledStriker.stickStyle = 'hook'
    controlledStriker.attributes = {
      speed: 0.96,
      control: 0.82,
      passing: 0.52,
      shooting: 1.02,
      defense: 0.38,
      power: 0.78,
      accuracy: 0.88,
      reaction: 0.78,
      ballHandling: 0.7,
      toughness: 0.56,
    }
    controlledStriker.defenseTendencies = {
      truckAggression: 0.24,
      slashAggression: 0.46,
      fumblePressurePreference: 0.55,
    }
  }

  return {
    mode: 'match3v3',
    controlledPlayer: 'auto',
    formations: {
      A: 'balanced',
      B: 'brutePress',
    },
    strategies: {
      A: {
        offenseScheme: 'behindNet',
        defenseScheme: 'zoneTriangle',
        transitionScheme: 'safeOutlet',
      },
      B: {
        offenseScheme: 'crashNet',
        defenseScheme: 'highPress',
        transitionScheme: 'counterAttack',
      },
    },
    players,
    field: {
      arenaWidth: 940,
      arenaHeight: 1460,
      playerVisualScale: 0.76,
      playerPhysicsRadius: 23,
      stickVisualScale: 0.58,
      stickGameplayScale: 0.7,
      coreRadius: 11,
      coreDensity: 0.0026,
      coreRestitution: 0.86,
      goalWidth: 125,
      goalPostRadius: 11,
      goalPostRestitution: 0.82,
      goalInsetFromEnd: 300,
      keeperZoneRadius: 210,
      innerNoBodyRadius: 40,
      keeperZoneBoundaryBuffer: 8,
      keeperZonePushStrength: 0.85,
      scoringPlaneTolerance: 5,
    },
    wall: {
      wallRestitution: 0.94,
      wallFriction: 0.02,
      wallThickness: 64,
      coreWallBounceMultiplier: 1.05,
      maxWallBounceSpeed: 21,
      minWallBounceSpeed: 3.2,
      coreOutOfBoundsMargin: 30,
      coreRecoveryDelayMs: 300,
      coreSafetyBounceEnabled: true,
      coreSafetyBounceImpulse: 4.5,
      coreSafetyResetToCenterAfterMs: 1000,
      wallCarryFumbleEnabled: true,
      wallCarryImpactSpeedThreshold: 2.8,
      wallCarryFumblePressure: 0.28,
      wallCarryOverchargeMultiplier: 1.75,
      wallCarryPinnedTimeMs: 900,
      wallCarryPinnedFumblePressure: 0.45,
      wallCarryBrushGraceSpeed: 1.2,
      wallFumblePopInwardImpulse: 4,
      wallPinDetectionDistance: 12,
      wallPinVelocityThreshold: 0.8,
      wallImpactVfxEnabled: true,
      bankShotTrackingEnabled: true,
    },
    keeper: {
      keeperEquipmentType: 'shield',
      keeperShieldWidth: 58,
      keeperShieldDepth: 24,
      keeperShieldDeflectForce: 5,
      keeperShieldDeflectDamping: 0.35,
      keeperShieldClearForce: 8,
      keeperShieldTrapTimeMs: 300,
      keeperShieldMaxDeflectAngle: 1.15,
      keeperShieldOwnGoalSafetyBias: 0.85,
      keeperControlMode: 'keeperOnPossession',
      keeperTightTargetRadiusRatio: 0.25,
      keeperBalancedTargetRadiusRatio: 0.5,
      keeperSweeperTargetRadiusRatio: 0.75,
      keeperReactionMultiplier: 1.25,
      keeperThreatLookaheadMs: 240,
      keeperReturnHomeSpeed: 0.72,
      keeperClearAggression: 0.86,
      keeperDeflectAggression: 0.9,
      keeperClearUsesThreatVector: true,
      keeperOwnGoalPreventionEnabled: true,
      keeperClearMinAwayDot: 0.25,
      keeperClearLateralVariance: 0.2,
      keeperClearTowardCenterBias: 0.6,
      keeperOrbitSmoothing: 3.4,
      keeperMaxLateralSpeed: 5.6,
      keeperHumanBiasEnabled: true,
      keeperHumanBiasStrength: 0.25,
      keeperHumanLateralBiasStrength: 0.35,
      keeperHumanDepthBiasStrength: 0.2,
      keeperHumanBiasMaxOffset: 25,
      keeperHumanBiasDecay: 7,
      autoSwitchOnLooseBall: false,
      looseBallSwitchCooldownMs: 1500,
      keeperAutoSwitchOnPossession: true,
      keeperAutoSwitchOnThreat: false,
      keeperAutoSwitchOnLooseBall: false,
      preventRapidSwitching: true,
      controlSwitchCooldownMs: 900,
      minControlOwnershipMs: 1000,
      keeperPossessionSwitchDelayMs: 0,
      keeperReturnToFieldAfterReleaseMs: 650,
      autoSwitchDistanceAdvantageRequired: 9999,
      keeperAutoSwitchThreatRadius: 205,
    },
    spacing: {
      maxCorePressersPerTeam: 1,
      presserSwitchCooldownMs: 900,
      presserDistanceAdvantageRequired: 60,
      supportMinSpacingFromCarrier: 140,
      supportPreferredSpacing: 210,
      avoidClusterRadius: 130,
      teammateRepulsionStrength: 0.45,
      possessionOffenseTransitionMs: 220,
      possessionDefenseTransitionMs: 400,
      offenseSupportMinSpacingFromCarrier: 158,
      offenseSupportPreferredSpacing: 240,
      offenseAvoidClusterRadius: 152,
      offenseTeammateRepulsionStrength: 0.6,
      enableBehindGoalCuts: true,
      behindGoalCutChanceSupport: 0.35,
      behindGoalCutChanceStriker: 0.45,
      frontSlotSpacing: 120,
      bankShotPreference: 0.35,
      tacticalJobSwitchCooldownMs: 700,
      highPressAggression: 0.82,
      lowBlockDepth: 0.34,
    },
    aiTactics: {
      tacticalOverrideEnabled: true,
      jobTargetStrictness: 0.55,
      emergencyGatherRadius: 75,
      receiverCatchRadius: 95,
      passLaneMinScore: 0.45,
      supportPassBias: 0.25,
    },
    aiOffense: {
      aiCarrierMinCommitMs: 350,
      aiCarrierMaxCommitMs: 2100,
      aiCarrierReevaluateAfterMs: 650,
      aiAimTurnRateRadiansPerSec: 6,
      aiCarrierBodyTurnRateRadiansPerSec: 2.6,
      aiMaxCarryMs: 2950,
      aiSpinDetectionEnabled: true,
      aiSpinAngularVelocityThreshold: 4.5,
      aiSpinDurationMs: 650,
      aiSpinMinimumRotationRadians: 5.2,
      aiCarrySideCommitMs: 900,
      aiClearChargeMinMs: 250,
      aiClearChargeMaxMs: 550,
      aiPassChargeMinMs: 500,
      aiPassChargeMaxMs: 800,
      aiDirectShotChargeMinMs: 900,
      aiDirectShotChargeMaxMs: 1200,
      aiBankShotChargeMinMs: 1150,
      aiBankShotChargeMaxMs: 1500,
      freezeCarrierTacticalJob: true,
      opponentAiScoringAggression: 0.75,
      opponentAiShotFrequency: 0.7,
      opponentAiBankShotFrequency: 0.45,
      opponentAiPassToShotBias: 0.55,
      opponentAiForceShotAfterMs: 2450,
      opponentAiAimAssist: 0.55,
      opponentAiShotError: 0.18,
      opponentAiDecisionIntervalMs: 180,
      opponentAiAttackSpacing: 120,
      aiDirectShotTargetOffsetRatio: 0.2,
      aiGoodDirectShotThreshold: 0.62,
      aiGoodBankShotThreshold: 0.55,
      aiPassBetterShotMargin: 0.18,
      aiMaxCarryBeforeShotMs: 2450,
      aiPossessionSettleMs: 550,
      aiShotCooldownMs: 500,
      aiMinShotDistance: 120,
      aiCloseRangeShotBonus: 0.2,
      aiBankShotsEnabled: true,
      aiBankShotPreference: 0.45,
      aiBankShotMinScore: 0.55,
      aiBankShotAttemptChanceWhenBlocked: 0.55,
      aiBankShotAttemptChanceWhenOpen: 0.18,
      aiBankShotAimAssist: 0.6,
      aiBankShotMaxError: 0.25,
      aiBankShotMinCarrierDistanceFromGoal: 150,
      aiBankShotWallTargetPadding: 40,
      aiSeekBetterShotAngleEnabled: true,
      aiShotBlockedThreshold: 0.55,
      aiLateralAttackMoveStrength: 0.72,
      aiLateralRepositionEnabled: true,
      aiLateralRepositionDistance: 120,
      aiLateralRepositionTimeMs: 500,
      aiWeakSideLanePreference: 0.5,
      aiBehindGoalPlayPreference: 0.45,
      aiFrontSlotFinishPreference: 0.6,
      aiBehindGoalPassEnabled: true,
      aiFrontSlotPassEnabled: true,
      aiShotPatienceMs: 520,
      aiForceShotAfterMs: 2450,
    },
    clearSafety: {
      ownGoalPreventionEnabled: true,
      ownGoalClearPathCheckEnabled: true,
      ownGoalDangerConeRadians: 0.75,
      ownGoalClearMinAwayDot: 0.25,
      safeClearSideBias: 0.45,
      safeClearMidfieldBias: 0.55,
      safeClearTeammateBias: 0.25,
      safeClearRandomVariance: 0.12,
      blockClearIntoOwnGoalHard: true,
      defensiveDeflectionSafetyEnabled: true,
      defensiveDeflectionAwayBias: 0.7,
      keeperShieldAwayBias: 0.85,
      defenderStickAwayBias: 0.55,
      nearOwnGoalSafetyRadius: 260,
    },
    tacticalGuides: {
      tacticalGuidesEnabled: true,
      tacticalGuideAlpha: 0.18,
      tacticalGuideRadius: 24,
      tacticalGuideShowLabels: false,
      tacticalGuideOnlyHumanTeam: false,
    },
    creaseBattle: {
      creaseBattleBreakerEnabled: true,
      creaseBattleTimeMs: 1400,
      creaseBattleLowSpeedThreshold: 1.8,
      creaseBattleClearImpulse: 7.5,
      creaseBattleSideBias: 0.35,
    },
    keeperZoneRules: {
      defendersAllowedInOwnKeeperZone: true,
      attackersBlockedFromOpponentKeeperZone: true,
      innerRingBlocksAllPlayers: true,
      maxDefensiveCleanersInZone: 1,
      defensiveCleanupRadius: 120,
      defensiveCleanupPriority: 0.75,
      creaseOutletSpacing: 130,
    },
    stick: {
      stanceResetEnabled: true,
      stanceResetDelayMs: 120,
      stanceReturnSmoothing: 12,
      runningStanceOffsetRadians: 0.55,
      aimOnlyWhileActionHeld: true,
      carryControlEnabled: true,
      carrySocketLag: 0.08,
      carrySocketMaxOffset: 18,
      carrySocketLateralRange: 16,
      carrySocketForwardRange: 10,
      carrySwayAmount: 0.18,
      carrySwaySmoothing: 12,
      carryControlDeadzone: 0.12,
      carryControlResponsiveness: 10,
      carryAimBlend: 0.35,
      carryPoseOffsetRadians: 0.45,
      carryPoseMaxArcRadians: 0.65,
      carryPoseSmoothing: 14,
      carryPoseRotationLimit: 6.5,
      activeGatherEnabled: true,
      activeGatherRadius: 84,
      activeGatherStrength: 0.58,
      activeGatherMaxSpeed: 16,
      activeGatherFunnelAngle: 1.65,
      activeGatherSnapRadius: 44,
      activeGatherSnapEnabled: true,
      passiveGatherEnabled: true,
      passiveGatherRadius: 52,
      passiveGatherStrength: 0.26,
      passiveGatherMaxSpeed: 9.5,
      passiveGatherFunnelAngle: 1.1,
      humanCloseGatherRadius: 30,
      humanPassiveCloseGatherRadius: 20,
      releaseRegrabCooldownMs: 180,
      fumbleRegrabCooldownMs: 260,
      gatherAttemptCooldownMs: 30,
      failedGatherGraceMs: 160,
      gatherOverridesStanceReset: true,
      catchReadyMinHoldMs: 120,
      catchReadyExitDelayMs: 80,
      stanceResetDoesNotCancelGather: true,
      chargeLoadbackDistance: 18,
      hardChargeEnabled: true,
      hardChargeHoldMs: 1250,
      hardChargeMultiplier: 1.15,
      playerChargeAuraEnabled: true,
      playerChargeAuraThreshold: 0.72,
      maxCradleEntrySpeed: 34,
      cradleMinRadius: 26,
      cradleMaxRadius: 88,
      cradleMinAngle: 8,
      cradleMaxAngle: 74,
      cradleCaptureRadius: 52,
      cradleAssistRadius: 66,
      cradleAssistStrength: 0.28,
      cradleAssistMaxSpeed: 3.4,
      stableCradleMs: 650,
      chargeCradleMs: 1250,
      overchargeMs: 1850,
      fumbleMs: 2500,
      passiveNudgeForce: 0.34,
      activeSwingForce: 5.4,
      maxDeflectImpulse: 5.2,
      releaseForceMin: 7.2,
      releaseForceMax: 17.2,
      chargeForceExponent: 1.25,
      overchargeAccuracyPenalty: 0.16,
      chargeLoadbackMinRadians: 0.08,
      chargeLoadbackMaxRadians: 0.78,
      chargeLoadbackSmoothing: 13,
      overchargeJitterAmount: 0.06,
      overchargeJitterSpeed: 18,
      releaseWindupMs: 0,
      releaseSwingMs: 90,
      releaseFollowThroughMs: 120,
      releaseSwingArcRadians: 0.95,
      releasePointNormalized: 0.55,
      releaseTangentialForceMultiplier: 0.32,
      releaseForwardForceMultiplier: 0.88,
      releaseSpinInfluence: 0.18,
      stickTotalLength: 84,
      stickHandleWidth: 9,
      stickPocketWidth: 1,
      stickPocketDepth: 29,
      stickLipThickness: 1,
      stickHandleLength: 1,
      stickInnerHighlight: 0.78,
      stickInnerHighlightWidth: 4,
      stickOutlineAlpha: 0.94,
      stickOutlineWidth: 3,
      stickWoodGrainAlpha: 0.08,
      swingTrailAlpha: 0.54,
      swingTrailDuration: 155,
      aimSmoothing: 15,
      maxStickRotationSpeed: 6.8,
      cradleFacingOffsetRadians: -0.35,
      stickStanceOffsetRadians: 0.55,
      handednessStickOffset: 9,
      handednessMirrorMultiplier: 1,
      loadbackAffectsAim: false,
      visualStickControlsImpulse: false,
    },
    defense: {
      truckEnabled: true,
      slashEnabled: true,
      truckCooldownMs: 1200,
      truckStartupMs: 80,
      truckActiveMs: 160,
      truckRecoveryMs: 380,
      truckRange: 78,
      truckArcRadians: 0.95,
      truckLungeImpulse: 4.8,
      truckBodyImpulse: 5.2,
      truckFumblePressure: 0.38,
      truckOverchargeMultiplier: 1.85,
      bruteTruckMultiplier: 1.45,
      nonBruteTruckMultiplier: 0.58,
      truckMissRecoveryMovement: 0.58,
      truckOffBallSpeedBoostAllowed: true,
      slashCooldownMs: 650,
      slashStartupMs: 45,
      slashActiveMs: 110,
      slashRecoveryMs: 180,
      slashArcRadians: 1.2,
      slashRange: 84,
      slashFumblePressure: 0.32,
      slashOverchargeMultiplier: 1.75,
      slashFreeCoreImpulse: 3.2,
      slashBodyImpulse: 0.25,
      supportSlashPrecisionMultiplier: 1.25,
      bruteSlashPowerMultiplier: 1.05,
      fumblePressureThreshold: 1.12,
      fumblePressureDecayPerSecond: 0.28,
      overchargeFumbleVulnerability: 1.7,
      stableCradleFumbleResistance: 0.78,
      chargingFumbleResistance: 0.94,
      bruteFumbleBonus: 0.22,
      supportStealBonus: 0.16,
    },
    matchFlow: {
      enableGoalCelebration: true,
      goalCelebrationMs: 1200,
      goalFlashDurationMs: 720,
      goalTextDurationMs: 1050,
      enableResetCountdown: true,
      resetCountdownStart: 3,
      resetCountdownStepMs: 700,
    },
  }
}

function defaultDefenseTendencies(
  role: 'keeper' | 'striker' | 'support' | 'brute',
): {
  truckAggression: number
  slashAggression: number
  fumblePressurePreference: number
} {
  switch (role) {
    case 'brute':
      return {
        truckAggression: 1,
        slashAggression: 0.55,
        fumblePressurePreference: 1,
      }
    case 'support':
      return {
        truckAggression: 0.2,
        slashAggression: 0.92,
        fumblePressurePreference: 0.86,
      }
    case 'keeper':
      return {
        truckAggression: 0.35,
        slashAggression: 0.82,
        fumblePressurePreference: 0.78,
      }
    default:
      return {
        truckAggression: 0.38,
        slashAggression: 0.68,
        fumblePressurePreference: 0.68,
      }
  }
}
