import { playerArchetypes } from '../data/playerArchetypes'
import { teams } from '../data/teams'
import type { LabTuningState } from '../lab/LabConfig'
import {
  DEFAULT_ARENA_PLAYER_RENDER_SCALE,
  DEFAULT_ARENA_STICK_RENDER_SCALE,
} from '../arena/ArenaCharacterAssets'
import { arenaProceduralAnimationDefaults } from '../rendering/ArenaProceduralAnimation'

export function createDefaultLabTuning(): LabTuningState {
  const players: LabTuningState['players'] = Object.fromEntries(
    teams.flatMap((team) =>
      team.roster.map((entry) => [
        entry.id,
        {
          id: entry.id,
          role: entry.role,
          playStyle: entry.playStyle,
          handedness: entry.handedness,
          stickStyle: entry.stickStyle,
          attributes: {
            ...playerArchetypes[entry.archetypeId].attributes,
          },
          defenseTendencies: defaultDefenseTendencies(entry.role),
        },
      ]),
    ),
  )
  const controlledStriker = players['a-striker']

  if (controlledStriker) {
    controlledStriker.role = 'striker'
    controlledStriker.playStyle = 'aggressive'
    controlledStriker.handedness = 'right'
    controlledStriker.stickStyle = 'hook'
    controlledStriker.attributes = {
      speed: 0.96,
      control: 0.82,
      passing: 0.52,
      shooting: 1.02,
      defense: 0.38,
      power: 0.78,
      accuracy: 0.88,
      reaction: 0.78,
      ballHandling: 0.7,
      toughness: 0.56,
    }
    controlledStriker.defenseTendencies = {
      truckAggression: 0.24,
      slashAggression: 0.46,
      fumblePressurePreference: 0.55,
    }
  }

  return {
    mode: 'match3v3',
    controlledPlayer: 'auto',
    formations: {
      A: 'balanced',
      B: 'brutePress',
    },
    strategies: {
      A: {
        offenseScheme: 'behindNet',
        defenseScheme: 'zoneTriangle',
        transitionScheme: 'safeOutlet',
      },
      B: {
        offenseScheme: 'crashNet',
        defenseScheme: 'highPress',
        transitionScheme: 'counterAttack',
      },
    },
    players,
    field: {
      arenaWidth: 1000,
      arenaHeight: 1600,
      playerVisualScale: 0.72,
      playerPhysicsRadius: 21.5,
      stickVisualScale: 0.58,
      stickGameplayScale: 0.7,
      coreRadius: 11,
      coreDensity: 0.0026,
      coreRestitution: 0.86,
      goalWidth: 125,
      goalPostRadius: 8,
      goalPostRestitution: 0.82,
      goalInsetFromEnd: 300,
      keeperZoneRadius: 210,
      innerNoBodyRadius: 40,
      keeperZoneBoundaryBuffer: 8,
      keeperZonePushStrength: 0.85,
      scoringPlaneTolerance: 6,
      goalScoreCooldownMs: 1000,
      useSweptGoalDetection: true,
      goalDetectionDebugEnabled: false,
    },
    wall: {
      wallRestitution: 0.94,
      wallFriction: 0.02,
      wallThickness: 64,
      coreWallBounceMultiplier: 1.05,
      maxWallBounceSpeed: 21,
      minWallBounceSpeed: 3.2,
      coreOutOfBoundsMargin: 30,
      coreRecoveryDelayMs: 300,
      coreSafetyBounceEnabled: true,
      coreSafetyBounceImpulse: 4.5,
      coreSafetyResetToCenterAfterMs: 1000,
      wallCarryFumbleEnabled: true,
      wallCarryImpactSpeedThreshold: 2.8,
      wallCarryFumblePressure: 0.28,
      wallCarryOverchargeMultiplier: 1.75,
      wallCarryPinnedTimeMs: 900,
      wallCarryPinnedFumblePressure: 0.45,
      wallCarryBrushGraceSpeed: 1.2,
      wallFumblePopInwardImpulse: 4,
      wallPinDetectionDistance: 12,
      wallPinVelocityThreshold: 0.8,
      wallImpactVfxEnabled: true,
      bankShotTrackingEnabled: true,
    },
    keeper: {
      keeperEquipmentType: 'shield',
      keeperShieldWidth: 42,
      keeperShieldDepth: 18,
      keeperShieldDeflectForce: 5,
      keeperShieldDeflectDamping: 0.35,
      keeperShieldClearForce: 8,
      keeperShieldTrapTimeMs: 300,
      keeperShieldMaxDeflectAngle: 1.15,
      keeperShieldOwnGoalSafetyBias: 0.92,
      keeperControlMode: 'keeperOnPossession',
      keeperTightTargetRadiusRatio: 0.25,
      keeperBalancedTargetRadiusRatio: 0.5,
      keeperSweeperTargetRadiusRatio: 0.75,
      keeperReactionMultiplier: 1.25,
      keeperThreatLookaheadMs: 240,
      keeperReturnHomeSpeed: 0.72,
      keeperClearAggression: 0.86,
      keeperDeflectAggression: 0.9,
      keeperClearUsesThreatVector: true,
      keeperOwnGoalPreventionEnabled: true,
      keeperClearMinAwayDot: 0.4,
      keeperClearLateralVariance: 0.2,
      keeperClearTowardCenterBias: 0.6,
      keeperOrbitSmoothing: 4.4,
      keeperMaxLateralSpeed: 6.6,
      keeperMoveSpeedMultiplier: 0.84,
      keeperAccelerationMultiplier: 1.05,
      keeperTurnRateMultiplier: 1.05,
      keeperReactionDelayMs: 75,
      keeperPredictionStrength: 0.78,
      keeperPostSaveRecoveryMs: 250,
      keeperFrontBackRecoveryMultiplier: 0.78,
      keeperRepositionDelayMs: 65,
      keeperHumanBiasEnabled: true,
      keeperHumanBiasStrength: 0.25,
      keeperHumanLateralBiasStrength: 0.35,
      keeperHumanDepthBiasStrength: 0.2,
      keeperHumanBiasMaxOffset: 25,
      keeperHumanBiasDecay: 7,
      autoSwitchOnLooseBall: false,
      looseBallSwitchCooldownMs: 1500,
      keeperAutoSwitchOnPossession: true,
      keeperAutoSwitchOnThreat: false,
      keeperAutoSwitchOnLooseBall: false,
      preventRapidSwitching: true,
      controlSwitchCooldownMs: 900,
      minControlOwnershipMs: 1000,
      keeperPossessionSwitchDelayMs: 0,
      keeperReturnToFieldAfterReleaseMs: 650,
      autoSwitchDistanceAdvantageRequired: 9999,
      keeperAutoSwitchThreatRadius: 205,
    },
    spacing: {
      maxCorePressersPerTeam: 1,
      presserSwitchCooldownMs: 780,
      presserDistanceAdvantageRequired: 60,
      supportMinSpacingFromCarrier: 150,
      supportPreferredSpacing: 235,
      avoidClusterRadius: 148,
      teammateRepulsionStrength: 0.52,
      possessionOffenseTransitionMs: 220,
      possessionDefenseTransitionMs: 400,
      offenseSupportMinSpacingFromCarrier: 185,
      offenseSupportPreferredSpacing: 295,
      offenseAvoidClusterRadius: 178,
      offenseTeammateRepulsionStrength: 0.74,
      enableBehindGoalCuts: true,
      behindGoalCutChanceSupport: 0.35,
      behindGoalCutChanceStriker: 0.45,
      frontSlotSpacing: 155,
      bankShotPreference: 0.42,
      tacticalJobSwitchCooldownMs: 580,
      highPressAggression: 0.82,
      lowBlockDepth: 0.34,
    },
    aiTactics: {
      tacticalOverrideEnabled: true,
      jobTargetStrictness: 0.68,
      emergencyGatherRadius: 82,
      receiverCatchRadius: 108,
      passLaneMinScore: 0.38,
      supportPassBias: 0.34,
    },
    aiOffense: {
      aiCarrierMinCommitMs: 280,
      aiCarrierMaxCommitMs: 1900,
      aiCarrierReevaluateAfterMs: 480,
      aiAimTurnRateRadiansPerSec: 6,
      aiCarrierBodyTurnRateRadiansPerSec: 2.6,
      aiMaxCarryMs: 2600,
      aiSpinDetectionEnabled: true,
      aiSpinAngularVelocityThreshold: 4.5,
      aiSpinDurationMs: 650,
      aiSpinMinimumRotationRadians: 5.2,
      aiCarrySideCommitMs: 700,
      aiClearChargeMinMs: 250,
      aiClearChargeMaxMs: 550,
      aiPassChargeMinMs: 260,
      aiPassChargeMaxMs: 520,
      aiDirectShotChargeMinMs: 760,
      aiDirectShotChargeMaxMs: 1060,
      aiBankShotChargeMinMs: 980,
      aiBankShotChargeMaxMs: 1320,
      freezeCarrierTacticalJob: true,
      opponentAiScoringAggression: 0.75,
      opponentAiShotFrequency: 0.78,
      opponentAiBankShotFrequency: 0.52,
      opponentAiPassToShotBias: 0.72,
      opponentAiForceShotAfterMs: 2150,
      opponentAiAimAssist: 0.55,
      opponentAiShotError: 0.18,
      opponentAiDecisionIntervalMs: 180,
      opponentAiAttackSpacing: 155,
      aiDirectShotTargetOffsetRatio: 0.42,
      aiGoodDirectShotThreshold: 0.5,
      aiGoodBankShotThreshold: 0.45,
      aiPassBetterShotMargin: 0.08,
      aiMaxCarryBeforeShotMs: 2150,
      aiPossessionSettleMs: 300,
      aiShotCooldownMs: 420,
      aiMinShotDistance: 120,
      aiCloseRangeShotBonus: 0.2,
      aiBankShotsEnabled: true,
      aiBankShotPreference: 0.45,
      aiBankShotMinScore: 0.5,
      aiBankShotAttemptChanceWhenBlocked: 0.65,
      aiBankShotAttemptChanceWhenOpen: 0.24,
      aiBankShotAimAssist: 0.6,
      aiBankShotMaxError: 0.25,
      aiBankShotMinCarrierDistanceFromGoal: 150,
      aiBankShotWallTargetPadding: 40,
      aiSeekBetterShotAngleEnabled: true,
      aiShotBlockedThreshold: 0.48,
      aiLateralAttackMoveStrength: 0.72,
      aiLateralRepositionEnabled: true,
      aiLateralRepositionDistance: 145,
      aiLateralRepositionTimeMs: 460,
      aiWeakSideLanePreference: 0.65,
      aiBehindGoalPlayPreference: 0.55,
      aiFrontSlotFinishPreference: 0.68,
      aiBehindGoalPassEnabled: true,
      aiFrontSlotPassEnabled: true,
      aiShotPatienceMs: 540,
      aiForceShotAfterMs: 2150,
    },
    clearSafety: {
      ownGoalPreventionEnabled: true,
      ownGoalClearPathCheckEnabled: true,
      ownGoalDangerConeRadians: 0.9,
      ownGoalClearMinAwayDot: 0.4,
      ownGoalProjectionDistance: 260,
      safeClearSideBias: 0.6,
      safeClearMidfieldBias: 0.45,
      safeClearTeammateBias: 0.25,
      safeClearRandomVariance: 0.12,
      blockClearIntoOwnGoalHard: true,
      defensiveDeflectionSafetyEnabled: true,
      defensiveDeflectionAwayBias: 0.85,
      keeperShieldAwayBias: 0.92,
      defenderStickAwayBias: 0.75,
      nearOwnGoalSafetyRadius: 300,
      ownGoalPanicClearPowerScale: 0.85,
    },
    tacticalGuides: {
      tacticalGuidesEnabled: true,
      tacticalGuideAlpha: 0.18,
      tacticalGuideRadius: 24,
      tacticalGuideShowLabels: false,
      tacticalGuideOnlyHumanTeam: false,
    },
    creaseBattle: {
      creaseBattleBreakerEnabled: true,
      creaseBattleTimeMs: 1400,
      creaseBattleLowSpeedThreshold: 1.8,
      creaseBattleClearImpulse: 7.5,
      creaseBattleSideBias: 0.35,
    },
    keeperZoneRules: {
      defendersAllowedInOwnKeeperZone: true,
      attackersBlockedFromOpponentKeeperZone: true,
      innerRingBlocksAllPlayers: true,
      maxDefensiveCleanersInZone: 1,
      defensiveCleanupRadius: 120,
      defensiveCleanupPriority: 0.75,
      creaseOutletSpacing: 130,
    },
    stick: {
      stanceResetEnabled: true,
      stanceResetDelayMs: 170,
      stanceReturnSmoothing: 10,
      runningStanceOffsetRadians: 0.48,
      aimOnlyWhileActionHeld: true,
      carryControlEnabled: true,
      carrySocketLag: 0.045,
      carrySocketMaxOffset: 13,
      carrySocketLateralRange: 12,
      carrySocketForwardRange: 8,
      carrySwayAmount: 0.1,
      carrySwaySmoothing: 12,
      carryControlDeadzone: 0.08,
      carryControlResponsiveness: 16,
      carryAimBlend: 0.25,
      carryPoseOffsetRadians: 0.38,
      carryPoseMaxArcRadians: 0.65,
      carryPoseSmoothing: 18,
      carryPoseRotationLimit: 8,
      activeGatherEnabled: true,
      activeGatherRadius: 96,
      activeGatherStrength: 0.7,
      activeGatherMaxSpeed: 19,
      activeGatherFunnelAngle: 1.9,
      activeGatherSnapRadius: 52,
      activeGatherSnapEnabled: true,
      passiveGatherEnabled: true,
      passiveGatherRadius: 58,
      passiveGatherStrength: 0.32,
      passiveGatherMaxSpeed: 11,
      passiveGatherFunnelAngle: 1.25,
      humanCloseGatherRadius: 38,
      humanPassiveCloseGatherRadius: 26,
      releaseRegrabCooldownMs: 180,
      fumbleRegrabCooldownMs: 260,
      gatherAttemptCooldownMs: 20,
      failedGatherGraceMs: 220,
      gatherOverridesStanceReset: true,
      catchReadyMinHoldMs: 70,
      catchReadyExitDelayMs: 120,
      stanceResetDoesNotCancelGather: true,
      chargeLoadbackDistance: 18,
      hardChargeEnabled: true,
      hardChargeHoldMs: 1100,
      hardChargeMultiplier: 1.15,
      playerChargeAuraEnabled: true,
      playerChargeAuraThreshold: 0.72,
      maxCradleEntrySpeed: 34,
      cradleMinRadius: 26,
      cradleMaxRadius: 88,
      cradleMinAngle: 8,
      cradleMaxAngle: 74,
      cradleCaptureRadius: 58,
      cradleAssistRadius: 74,
      cradleAssistStrength: 0.34,
      cradleAssistMaxSpeed: 4.4,
      stableCradleMs: 650,
      chargeCradleMs: 1100,
      overchargeMs: 1750,
      fumbleMs: 2500,
      passiveNudgeForce: 0.34,
      activeSwingForce: 5.4,
      maxDeflectImpulse: 5.2,
      releaseForceMin: 9.2,
      releaseForceMax: 19.8,
      chargeForceExponent: 1.25,
      overchargeAccuracyPenalty: 0.16,
      chargeLoadbackMinRadians: 0.08,
      chargeLoadbackMaxRadians: 0.78,
      chargeLoadbackSmoothing: 13,
      overchargeJitterAmount: 0.06,
      overchargeJitterSpeed: 18,
      releaseWindupMs: 0,
      releaseSwingMs: 75,
      releaseFollowThroughMs: 120,
      releaseSwingArcRadians: 0.95,
      releasePointNormalized: 0.55,
      releaseTangentialForceMultiplier: 0.32,
      releaseForwardForceMultiplier: 0.88,
      releaseSpinInfluence: 0.18,
      stickTotalLength: 84,
      stickHandleWidth: 9,
      stickPocketWidth: 1,
      stickPocketDepth: 29,
      stickLipThickness: 1,
      stickHandleLength: 1,
      stickInnerHighlight: 0.78,
      stickInnerHighlightWidth: 4,
      stickOutlineAlpha: 0.94,
      stickOutlineWidth: 3,
      stickWoodGrainAlpha: 0.08,
      swingTrailAlpha: 0.54,
      swingTrailDuration: 155,
      aimSmoothing: 15,
      maxStickRotationSpeed: 6.8,
      cradleFacingOffsetRadians: -0.35,
      stickStanceOffsetRadians: 0.55,
      handednessStickOffset: 9,
      handednessMirrorMultiplier: 1,
      loadbackAffectsAim: false,
      visualStickControlsImpulse: false,
    },
    defense: {
      truckEnabled: true,
      slashEnabled: true,
      truckCooldownMs: 1200,
      truckStartupMs: 80,
      truckActiveMs: 160,
      truckRecoveryMs: 380,
      truckRange: 78,
      truckArcRadians: 0.95,
      truckLungeImpulse: 4.8,
      truckBodyImpulse: 5.2,
      truckFumblePressure: 0.42,
      truckOverchargeMultiplier: 1.85,
      bruteTruckMultiplier: 1.45,
      nonBruteTruckMultiplier: 0.58,
      truckMissRecoveryMovement: 0.58,
      truckOffBallSpeedBoostAllowed: true,
      truckKnockdownThreshold: -0.02,
      truckKnockdownMs: 900,
      truckGetUpMs: 460,
      truckKnockdownImmunityMs: 900,
      truckKnockdownFumbleSpeed: 4.8,
      slashCooldownMs: 650,
      slashStartupMs: 45,
      slashActiveMs: 110,
      slashRecoveryMs: 180,
      slashArcRadians: 1.2,
      slashRange: 84,
      slashFumblePressure: 0.34,
      slashOverchargeMultiplier: 1.75,
      chargingSlashVulnerability: 1.75,
      overchargedSlashVulnerability: 2.1,
      stableSlashVulnerability: 0.82,
      releaseWindupSlashVulnerability: 1.2,
      releaseFrameProtectionMs: 70,
      chargingStealEnabled: true,
      slashCanInterruptCharge: true,
      slashChargeFumbleBaseChance: 0.58,
      slashOverchargeFumbleBaseChance: 0.7,
      slashFreeCoreImpulse: 3.2,
      slashBodyImpulse: 0.25,
      supportSlashPrecisionMultiplier: 1.25,
      bruteSlashPowerMultiplier: 1.05,
      fumblePressureThreshold: 1.05,
      fumblePressureDecayPerSecond: 0.28,
      overchargeFumbleVulnerability: 1.7,
      stableCradleFumbleResistance: 0.78,
      chargingFumbleResistance: 1.14,
      bruteFumbleBonus: 0.22,
      supportStealBonus: 0.2,
    },
    matchFlow: {
      enableMatchIntro: true,
      matchIntroMs: 950,
      initialCountdownStart: 3,
      initialCountdownStepMs: 650,
      enableGoalCelebration: true,
      goalCelebrationMs: 1200,
      goalFlashDurationMs: 720,
      goalTextDurationMs: 1050,
      enableResetCountdown: true,
      resetCountdownStart: 3,
      resetCountdownStepMs: 700,
    },
    arenaVisual: {
      themeId: 'rookie',
      calculatedAttendance: true,
      manualAttendance: 0.5,
      homeTeamId: 'team-a',
      awayTeamId: 'rookie-scrappers',
      homeCrestMode: 'team',
      homePrimaryColor: '#25b9c7',
      homeAccentColor: '#f2c84b',
      awayPrimaryColor: '#43a7d8',
      awayAccentColor: '#ffd34f',
      playerSkinColor: '#d59a6f',
      playerHairStyle: 'hair01',
      playerHairColor: '#674536',
      playerRole: 'striker',
      playerHandedness: 'right',
      characterRendererMode: 'asset',
      characterRendererScope: 'controlled',
      arenaBodyId: 'field-player-01',
      arenaHairId: 'arena-hair-01',
      arenaStickId: 'rookie-cesta-01',
      spriteScale: DEFAULT_ARENA_PLAYER_RENDER_SCALE,
      arenaStickScale: DEFAULT_ARENA_STICK_RENDER_SCALE,
      arenaStickAngle: 0,
      stickLayerMode: 'automatic',
      anchorOverlay: false,
      contractOverlay: false,
      corePocketAttachment: true,
      chargePreview: 0,
      forceFullyCharged: false,
      coreSpin: true,
      chargeVfx: true,
      simulateSlowLoading: false,
      forceMissingAssetFallback: false,
      showPreloadTimings: false,
      proceduralAnimation: arenaProceduralAnimationDefaults.enabled,
      hoverRunEnabled:
        arenaProceduralAnimationDefaults.hoverRunEnabled,
      footShuffle: arenaProceduralAnimationDefaults.footShuffle,
      playerScaleMultiplier:
        arenaProceduralAnimationDefaults.playerScaleMultiplier,
      idleBobAmount: arenaProceduralAnimationDefaults.idleBobAmount,
      movementBobAmount:
        arenaProceduralAnimationDefaults.movementBobAmount,
      movementBobSpeed:
        arenaProceduralAnimationDefaults.movementBobSpeed,
      squashStretchAmount:
        arenaProceduralAnimationDefaults.squashStretchAmount,
      leanAmount: arenaProceduralAnimationDefaults.leanAmount,
      lateralSwayAmount:
        arenaProceduralAnimationDefaults.lateralSwayAmount,
      shadowPulseAmount:
        arenaProceduralAnimationDefaults.shadowPulseAmount,
      coreTrackingEnabled:
        arenaProceduralAnimationDefaults.coreTrackingEnabled,
      naturalHoldMode: arenaProceduralAnimationDefaults.naturalHoldMode,
      legacyCoreMagnetMode:
        arenaProceduralAnimationDefaults.legacyCoreMagnetMode,
      frontArcDegrees: arenaProceduralAnimationDefaults.frontArcDegrees,
      sideReachArcDegrees:
        arenaProceduralAnimationDefaults.sideReachArcDegrees,
      readyCarriageAngle:
        arenaProceduralAnimationDefaults.readyCarriageAngle,
      stickBiasStrength:
        arenaProceduralAnimationDefaults.stickBiasStrength,
      stickClampAmount: arenaProceduralAnimationDefaults.stickClampAmount,
      stickFollowStrength:
        arenaProceduralAnimationDefaults.stickFollowStrength,
      stickMaxTurnRate:
        arenaProceduralAnimationDefaults.stickMaxTurnRate,
      stickLagClamp: arenaProceduralAnimationDefaults.stickLagClamp,
      slashWindupMs: arenaProceduralAnimationDefaults.slashWindupMs,
      slashSweepMs: arenaProceduralAnimationDefaults.slashSweepMs,
      slashRecoverMs: arenaProceduralAnimationDefaults.slashRecoverMs,
      slashArcDegrees: arenaProceduralAnimationDefaults.slashArcDegrees,
      slashAnimationSpeed:
        arenaProceduralAnimationDefaults.slashAnimationSpeed,
      chargeLoadAngleMax:
        arenaProceduralAnimationDefaults.chargeLoadAngleMax,
      releaseSnapAmount:
        arenaProceduralAnimationDefaults.releaseSnapAmount,
      releaseRecoilAmount:
        arenaProceduralAnimationDefaults.releaseRecoilAmount,
      quickPassThreshold:
        arenaProceduralAnimationDefaults.quickPassThreshold,
      firmPassThreshold:
        arenaProceduralAnimationDefaults.firmPassThreshold,
      heavyShotThreshold:
        arenaProceduralAnimationDefaults.heavyShotThreshold,
      fullChargeThreshold:
        arenaProceduralAnimationDefaults.fullChargeThreshold,
      slashTrailEnabled:
        arenaProceduralAnimationDefaults.slashTrailEnabled,
      releaseTrailEnabled:
        arenaProceduralAnimationDefaults.releaseTrailEnabled,
      fullChargeBurstEnabled:
        arenaProceduralAnimationDefaults.fullChargeBurstEnabled,
      animationSpeed:
        arenaProceduralAnimationDefaults.animationSpeedMultiplier,
      geometryOverlay: false,
      crowdAnimation: true,
      reducedMotion: false,
    },
  }
}

function defaultDefenseTendencies(
  role: 'keeper' | 'striker' | 'support' | 'brute',
): {
  truckAggression: number
  slashAggression: number
  fumblePressurePreference: number
} {
  switch (role) {
    case 'brute':
      return {
        truckAggression: 1,
        slashAggression: 0.55,
        fumblePressurePreference: 1,
      }
    case 'support':
      return {
        truckAggression: 0.2,
        slashAggression: 0.92,
        fumblePressurePreference: 0.86,
      }
    case 'keeper':
      return {
        truckAggression: 0.35,
        slashAggression: 0.82,
        fumblePressurePreference: 0.78,
      }
    default:
      return {
        truckAggression: 0.38,
        slashAggression: 0.68,
        fumblePressurePreference: 0.68,
      }
  }
}
