export const visualConfig = {
  bodyRadius: 21,
  headRadius: 18,
  headForwardOffset: 12,
  torsoLength: 31,
  torsoWidth: 31,
  legLength: 11,
  legWidth: 8,
  outlineColor: 0x071016,
  outlineAlpha: 0.9,
  outlineWidth: 3,
  skinColor: 0xf2bf91,
  skinShadeColor: 0xd89469,
  shadowColor: 0x02070a,
  shadowAlpha: 0.34,
  shadowWidth: 56,
  shadowHeight: 30,
  shadowOffsetY: 10,
  controlledRingRadius: 39,
  controlledRingColor: 0xffffff,
  controlledRingAlpha: 0.92,
  controlledRingWidth: 3,
  idleBobAmplitude: 1.8,
  idleBobSpeed: 0.0045,
  movementBobAmplitude: 2.8,
  roleScale: {
    keeper: {
      bodyX: 1.18,
      bodyY: 1.02,
      head: 1.02,
    },
    striker: {
      bodyX: 0.9,
      bodyY: 1.06,
      head: 0.96,
    },
    support: {
      bodyX: 1,
      bodyY: 1,
      head: 1,
    },
    brute: {
      bodyX: 1.26,
      bodyY: 1.08,
      head: 1.05,
    },
  },
  label: {
    roleOffsetY: 48,
    aiOffsetY: 64,
    roleFontSize: 15,
    aiFontSize: 12,
  },
  stick: {
    thickness: 12,
    outlineExtra: 5,
    tipAccentRadius: 6,
    forkSpread: 11,
    hammerHeadLength: 30,
    hammerHeadWidth: 12,
    whipSegments: 9,
  },
} as const
