export const visualConfig = {
  playerScale: 0.76,
  headRadius: 18,
  headForwardOffset: 12,
  torsoLength: 31,
  torsoWidth: 31,
  outlineColor: 0x071016,
  outlineAlpha: 0.94,
  outlineWidth: 3,
  skinColor: 0xf2bf91,
  skinShadeColor: 0xd89469,
  shadowColor: 0x02070a,
  shadowAlpha: 0.27,
  shadowWidth: 56,
  shadowHeight: 27,
  shadowOffsetY: 8,
  controlledRingRadius: 37,
  controlledRingColor: 0xffffff,
  controlledRingAlpha: 0.92,
  controlledRingWidth: 3,
  idleBobAmplitude: 1.15,
  idleBobSpeed: 0.0054,
  movementBobAmplitude: 2.15,
  roleScale: {
    keeper: {
      bodyX: 1.18,
      bodyY: 1.02,
      head: 1.02,
      shadow: 1.12,
    },
    striker: {
      bodyX: 0.9,
      bodyY: 1.06,
      head: 0.96,
      shadow: 0.92,
    },
    support: {
      bodyX: 1,
      bodyY: 1,
      head: 1,
      shadow: 1,
    },
    brute: {
      bodyX: 1.26,
      bodyY: 1.08,
      head: 1.05,
      shadow: 1.18,
    },
  },
  label: {
    roleOffsetY: 48,
    aiOffsetY: 64,
    roleFontSize: 15,
    aiFontSize: 12,
  },
  stick: {
    thickness: 12,
    outlineExtra: 5,
    tipAccentRadius: 6,
    forkSpread: 11,
    hammerHeadLength: 30,
    hammerHeadWidth: 12,
    whipSegments: 9,
    innerEdgeColor: 0xfff8cf,
    innerEdgeAlpha: 0.92,
    innerEdgeWidth: 3.5,
    innerEdgeOffset: 4,
    innerEdgeStart: 0.2,
    innerEdgeEnd: 0.82,
    socketGlowColor: 0xfff3a6,
    socketGlowRadius: 13,
    socketCoreRadius: 4,
  },
} as const
