export const wallConfig = {
  wallRestitution: 0.94,
  wallFriction: 0.02,
  wallThickness: 64,
  coreWallBounceMultiplier: 1.05,
  maxWallBounceSpeed: 21,
  minWallBounceSpeed: 3.2,
  coreOutOfBoundsMargin: 30,
  coreRecoveryDelayMs: 300,
  coreSafetyBounceEnabled: true,
  coreSafetyBounceImpulse: 4.5,
  coreSafetyResetToCenterAfterMs: 1000,
  wallCarryFumbleEnabled: true,
  wallCarryImpactSpeedThreshold: 2.8,
  wallCarryFumblePressure: 0.28,
  wallCarryOverchargeMultiplier: 1.75,
  wallCarryPinnedTimeMs: 900,
  wallCarryPinnedFumblePressure: 0.45,
  wallCarryBrushGraceSpeed: 1.2,
  wallFumblePopInwardImpulse: 4,
  wallPinDetectionDistance: 12,
  wallPinVelocityThreshold: 0.8,
  wallImpactVfxEnabled: true,
  wallImpactVfxMinSpeed: 3,
  bankShotTrackingEnabled: true,
  bankShotWindowMs: 2500,
}
