export type AppScreen =
  | 'boot'
  | 'mainMenu'
  | 'createPlayer'
  | 'playerProfile'
  | 'teamManagement'
  | 'teamLoadout'
  | 'leagueHub'
  | 'store'
  | 'settings'
  | 'match'
  | 'matchResults'
